### ISSUE TITLE
[Question] How to use golang module with ffi dart

### ISSUE THREAD

**Issue by winterdl** [huage2580/reader_parser2#1]
I could use golang with gomobile, but the project use direct from dart to golang, please share the experence about build golang to native and binds to dart. Thank you!

**Comment by huage2580** [comment]
i use `go build -buildmode=c-shared` for the project;  
such as build for Android:
```shell
$env:GOOS="android"
$env:GOARCH="arm64"
$env:CGO_ENABLED="1"
$env:CC="C:\Users\hua\AppData\Local\Android\Sdk\ndk\22.0.7026061\toolchains\llvm\prebuilt\windows-x86_64\bin\aarch64-linux-android21-clang.cmd"
$env:CXX="C:\Users\hua\AppData\Local\Android\Sdk\ndk\22.0.7026061\toolchains\llvm\prebuilt\windows-x86_64\bin\aarch64-linux-android21-clang++.cmd"
go build -buildmode=c-shared -o libevparser.so
```
sample in go for export.
```
//export Add
func Add(a int, b int) *C.char {
	var r = fmt.Sprintf("%d+%d=%d",a,b,a+b)
	return C.CString(r)
}
```

and then use the output `.h` file.
```
# dart run ffigen

ffigen:
  output: 'parser_bindings.dart'
  name: 'EVParser'
  headers:
    entry-points:
      - 'share/godll.h'
```
